import {useState,type FC,type ReactNode} from 'react'
import Img from '../components/ui/Img'
import {eventImg,portrait} from '../data/images'
import {H} from '../components/ui/PageTitle'
const Calender:FC<{go?:(p:string)=>void}>=({go})=>{const ev:Record<number,string>={3:'Design Conference',16:'Weekend Festival',25:'Glastonbury Festival'}
  return <><H t="Calender"/><div className="grid xl:grid-cols-[280px_1fr] gap-5"><div className="card space-y-4"><button className="btn w-full" onClick={()=>go?.('Add New Event')}>+ Add New Event</button><b>You are going to</b>{[['Design Conference','Today 07:19 AM','56 Davion Mission Suite 157'],['Weekend Festival','16 October 2019 at 5.00 PM','853 Moore Flats Suite 158'],['Glastonbury Festival','20-22 Oct 2019 at 6.00 PM','646 Walter Road Apt. 571'],['Ultra Europe 2019','25 October 2019 at 10.00 PM','906 Satterfield Tunnel Apt. 983']].map(([e,t,a],i)=><div key={e} className="border-b border-slate-100 dark:border-dline pb-3 flex gap-3"><Img src={eventImg(i)} alt="" className="w-10 h-10 rounded-full object-cover shrink-0"/><div className="min-w-0 text-xs"><b className="block text-[13px]">{e}</b><span className="block text-slate-400 truncate">{t}</span><span className="block text-slate-400 truncate">{a}</span><span className="flex -space-x-2 mt-2">{['Jason Price','Duane Dean','Jonathan Barker'].map(p=><Img key={p} src={portrait(p)} alt={p} className="w-6 h-6 rounded-full object-cover border-2 border-white dark:border-dcard"/>)}</span></div></div>)}</div>
  <div className="card overflow-x-auto"><h2 className="text-center font-bold text-lg mb-4">‹ October 2019 ›</h2><div className="grid grid-cols-7 min-w-[560px] text-center">{['MON','TUE','WED','THU','FRI','SAT','SUN'].map(d=><b key={d} className="bg-slate-100 dark:bg-dline py-2">{d}</b>)}
  {Array.from({length:35},(_,i)=>{const d=i-1;const ok=d>=1&&d<=31;return <div key={i} className={`h-20 border border-slate-100 dark:border-dline p-2 text-right ${ok?'':'text-slate-300'}`}>{ok?d:''}{ev[d]&&<p className="text-[10px] text-left bg-violet-100 text-violet-600 rounded px-1 mt-1 truncate">{ev[d]}</p>}</div>})}</div></div></div></>}
export default Calender
