import type {FC} from 'react'
import Dashboard from './Dashboard'
import Products from './Products'
import Favorites from './Favorites'
import Inbox from './Inbox'
import OrderLists from './OrderLists'
import ProductStock from './ProductStock'
import Pricing from './Pricing'
import Calender from './Calender'
import Todo from './Todo'
import Contact from './Contact'
import Invoice from './Invoice'
import UIElements from './UIElements'
import Team from './Team'
import TablePage from './TablePage'
import Settings from './Settings'
import AddContact from './AddContact'
import AddTeamMember from './AddTeamMember'
import AddEvent from './AddEvent'
import AddTodo from './AddTodo'
import Login from './Login'
import Signup from './Signup'
import NotFound from './NotFound'
export const pageComponents:Record<string,FC<any>>={'Dashboard':Dashboard,'Products':Products,'Favorites':Favorites,'Inbox':Inbox,'Order Lists':OrderLists,'Product Stock':ProductStock,'Pricing':Pricing,'Calender':Calender,'To-Do':Todo,'Contact':Contact,'Invoice':Invoice,'UI Elements':UIElements,'Team':Team,'Table':TablePage,'Settings':Settings,'Add New Contact':AddContact,'Add Team Member':AddTeamMember,'Add New Event':AddEvent,'Add New To-Do':AddTodo,'Login':Login,'Create Account':Signup,'404':NotFound}
